'use client';
import { useState } from 'react';
import type { InvestigationResponse } from '@/lib/types';

interface Props {
  investigation:  InvestigationResponse;
  onMarkResolved?: () => void;
  resolved?:      boolean;
}

/* ── helpers ─────────────────────────────────────────────────────────────── */
function str(v: unknown, fallback = ''): string {
  return typeof v === 'string' ? v : fallback;
}
function strArr(v: unknown): string[] {
  return Array.isArray(v) ? (v as unknown[]).map(x => str(x)) : [];
}

function buildMarkdown(inv: InvestigationResponse): string {
  const NL  = '\n';
  const rep = inv.report as Record<string, unknown> | null | undefined;
  const parts: string[] = [
    '# DevOps Incident Report', '',
    '**Session:** '   + inv.session_id,
    '**Category:** '  + inv.issue_category,
    '**Severity:** '  + inv.severity.toUpperCase(),
    '**Iteration:** ' + String(inv.iteration),
    '**Status:** '    + String(inv.status ?? 'in_progress'),
    '', '## Probable Root Causes',
    ...inv.probable_causes.map(c =>
      '- **' + c.cause + '** (' + Math.round(c.confidence * 100) + '% confidence)'
    ),
    '', '## Affected Services',
    inv.affected_services.join(', ') || 'None identified',
    '', '## Error Codes',
    inv.error_codes.join(', ') || 'None',
    '', '## Diagnostic Steps',
    ...inv.diagnostic_steps.map(s =>
      '### Step ' + String(s.step_number) + ': ' + s.purpose + NL +
      '```' + NL + s.command + NL + '```' + NL +
      'Expected: ' + s.expected_result
    ),
    '', '## Recommended Fixes',
    ...inv.recommended_fixes.map(f =>
      '### ' + f.title + NL + f.description + NL +
      f.steps.map((st, i) => String(i + 1) + '. ' + st).join(NL)
    ),
    '', '---',
    '**Lessons learned:** ' + strArr(rep?.lessons_learned).join('; '),
    '*Generated by Agentic DevOps Troubleshooting Assistant*',
  ];
  return parts.join(NL);
}

const SEV: Record<string, string> = {
  critical: 'bg-red-900/40 text-red-300 border-red-700/50',
  high:     'bg-orange-900/40 text-orange-300 border-orange-700/50',
  medium:   'bg-yellow-900/40 text-yellow-300 border-yellow-700/50',
  low:      'bg-green-900/40 text-green-300 border-green-700/50',
  unknown:  'bg-gray-800 text-gray-400 border-gray-600',
};

export default function FinalReport({ investigation: inv, onMarkResolved, resolved }: Props) {
  const [copied, setCopied] = useState(false);

  const rep          = inv.report as Record<string, unknown> | null | undefined;
  const reportTitle  = str(rep?.title, 'Investigation Report');
  const execSummary  = str(rep?.executive_summary);
  const timeline     = strArr(rep?.timeline);
  const lessons      = strArr(rep?.lessons_learned);
  const prevention   = strArr(rep?.prevention_measures);

  const handleCopy = () => {
    navigator.clipboard.writeText(buildMarkdown(inv));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([buildMarkdown(inv)], { type: 'text/markdown' });
    const url  = URL.createObjectURL(blob);
    const a    = Object.assign(document.createElement('a'), {
      href: url, download: 'incident-' + inv.session_id.slice(0, 8) + '.md',
    });
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-900 border border-gray-700 rounded-xl p-5 space-y-5"
      role="region" aria-label="Final Investigation Report">

      {/* Header */}
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="space-y-1">
          <h2 className="text-xl font-bold text-white">{reportTitle}</h2>
          <div className="flex items-center gap-2 flex-wrap">
            <span className={'text-xs px-2 py-0.5 rounded border font-medium ' + (SEV[inv.severity] ?? SEV.unknown)}>
              {inv.severity.toUpperCase()}
            </span>
            <span className="text-xs text-gray-500">
              Session: {inv.session_id.slice(0, 12)}&hellip;
            </span>
            <span className="text-xs text-gray-500">Iteration {inv.iteration}</span>
            {resolved && (
              <span className="text-xs text-green-400 bg-green-900/30 border border-green-700/40 px-2 py-0.5 rounded">
                Resolved
              </span>
            )}
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-2 flex-wrap">
          <button onClick={handleCopy}
            className="text-xs px-3 py-1.5 rounded-lg border border-gray-600 text-gray-300
              hover:border-blue-500 hover:text-blue-300 transition-colors">
            {copied ? 'Copied!' : 'Copy Report'}
          </button>
          <button onClick={handleDownload}
            className="text-xs px-3 py-1.5 rounded-lg border border-gray-600 text-gray-300
              hover:border-green-500 hover:text-green-300 transition-colors">
            Download .md
          </button>
          {onMarkResolved && !resolved && (
            <button onClick={onMarkResolved}
              className="text-xs px-3 py-1.5 rounded-lg bg-green-700 hover:bg-green-600
                text-white font-medium transition-colors">
              Mark Resolved
            </button>
          )}
        </div>
      </div>

      {/* Executive summary */}
      {execSummary && (
        <div className="bg-blue-900/20 border border-blue-700/30 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-blue-300 mb-2">Executive Summary</h3>
          <p className="text-sm text-gray-300 leading-relaxed">{execSummary}</p>
        </div>
      )}

      {/* Key metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {([
          ['Issue Category',    inv.issue_category],
          ['Affected Services', String(inv.affected_services.length)],
          ['Root Causes Found', String(inv.probable_causes.length)],
          ['Error Codes',       inv.error_codes.join(', ') || 'None'],
        ] as [string, string][]).map(([label, value]) => (
          <div key={label} className="bg-gray-800 rounded-lg p-3 border border-gray-700">
            <p className="text-xs text-gray-500 mb-1">{label}</p>
            <p className="text-sm font-medium text-white truncate">{value}</p>
          </div>
        ))}
      </div>

      {/* Timeline */}
      {timeline.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-white mb-2">Timeline</h3>
          <ol className="space-y-1">
            {timeline.map((item, i) => (
              <li key={i} className="text-xs text-gray-400 flex gap-2">
                <span className="text-gray-600 shrink-0">{i + 1}.</span>{item}
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Lessons learned */}
      {lessons.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-white mb-2">Lessons Learned</h3>
          <ul className="space-y-1">
            {lessons.map((l, i) => (
              <li key={i} className="text-xs text-gray-400 flex gap-2">
                <span className="text-blue-500 shrink-0">+</span>{l}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Prevention measures */}
      {prevention.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-white mb-2">Prevention Measures</h3>
          <ul className="space-y-1">
            {prevention.map((p, i) => (
              <li key={i} className="text-xs text-gray-400 flex gap-2">
                <span className="text-green-500 shrink-0">+</span>{p}
              </li>
            ))}
          </ul>
        </div>
      )}

      <p className="text-xs text-gray-600 border-t border-gray-700/50 pt-3">
        Generated by Agentic DevOps Troubleshooting Assistant &middot; Session {inv.session_id}
      </p>
    </div>
  );
}
